/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Espacedonneur (void);
GtkWidget* create_GestionRDV (void);
GtkWidget* create_ModificationRDV (void);
GtkWidget* create_Modificationundonneur (void);
GtkWidget* create_AjouterRDV (void);
GtkWidget* create_SuppRDV (void);
GtkWidget* create_AssurerSuppRDV (void);
GtkWidget* create_Affichageundon (void);
GtkWidget* create_rdv_stat (void);
